### ISSUE TITLE
Multi-language passage cover problem

### ISSUE THREAD

**Issue by jackwu925** [hugo-themes/toha#1022]
I found that only if the English version exists can the other language version's cover exists.
For example, if you want to exhibit the cover picture in other language version's mode, you have to creat the file "index.md" which is in English language in the same folder, then the cover photo can be shown in other language's mode. Here I choose the Chinese version:

Before creating the "index.md":
![1](https://github.com/user-attachments/assets/3f8d91d9-f275-4b9f-99e9-1cf5d038b488)

After creating "index.md":
![image](https://github.com/user-attachments/assets/7673369c-6aca-4f9c-b62e-9bf6b57fc008)

By the way, after creating the "index.md" file, the English version web will also show this page and it seems that we cannot hide it.

Do we have any approach to solve this problem? Some contents in English are not necessary but essential in other languages.

**Comment by hossainemruz** [comment]
Does specifying the hero image explicitly in front-matter work? Something like this?
```yaml
---
title: "Rich Content"
date: 2020-06-08T08:06:25+06:00
description: Sample post with multiple images, embedded video etc.
menu:
  sidebar:
    name: Rich Content
    identifier: rich-content
    parent: sub-category
    weight: 10
hero: images/forest.jpg
tags:
- Markdown
- Content Organization
- Multi-lingual
categories:
- Basic
---
```
