### ISSUE TITLE
Set mermaid dark theme automatically

### ISSUE THREAD

**Issue by BernatBC** [hugo-themes/toha#1042]
This theme has mermaid support. As we can check in the [toha guide's mermaid post](https://toha-guides.netlify.app/posts/writing-posts/mermaid/), when setting the site theme to dark, graphs are unreadable.

![Image](https://github.com/user-attachments/assets/7761ae21-b555-4bd1-99df-ca003c2eca3d)

### Describe the solution you'd like

The solution that I thought would be to set up the following:

- For site light theme: Use `default` mermaid theme
- For site dark theme: Use `dark` mermaid theme

Of course, there should be the option to override them.

Globally:

```yaml
flowchart:
      enable: true
      services:
        # Uncomment for `mermaid` shortcode.
        mermaid:
          # For config options, see: https://mermaid-js.github.io/mermaid/#/Setup?id=configuration
          theme: default
          darkTheme: dark
```

Per graph:

```go
{{< mermaid align="center" >}}
%%{init: {'theme':'default', 'darkTheme':'dark'}}%%
  # your mermaid content here
{{< /mermaid >}}
```
