### ISSUE TITLE
[Feature Request] Specify which folders in ToC are expanded by default

### ISSUE THREAD

**Issue by michjnich** [hugo-themes/toha#576]
### Allow ToC to expand sections by default
Say I have a posts structure as follows:

```
Posts
-- Tech
-- -- 2022
-- -- 2021
-- -- 2020
-- Personal
-- -- 2022
```

At the moment, when I go into posts I will see `Tech` and `Personal` at the top level. I would also like to see the expanded view of `Tech` though, and possibly even the expanded view of the most recent year (2022). 

### Describe alternatives you've considered
The solution I was considering was to add a parameter to the `_index.md` file for these folders to set `expand`. The default would be `false` (as is) and would only change if explicitly set. 

So, eg. 

```
---
title: Technology
menu:
  sidebar:
    name: Tech
    identifier: tech
    expand: true
    weight: 1000
---
```

If this is set then the section is expanded by default when the page is created. 

### Additional context
N/A
