### ISSUE TITLE
softSkills section working backwards?

### ISSUE THREAD

**Issue by davidgs** [hugo-themes/toha#986]
## Expected Behavior
In the `softSkills` section, the color indicator should go around and stop at the defined percentage. Instead, it is now going around and leaving the remainder only. 
![2024-09-26_15-13-29](https://github.com/user-attachments/assets/0f3e2387-f93a-48e7-a9ae-1d3325458158)
![2024-09-26_15-14-30](https://github.com/user-attachments/assets/2a1e71fb-16c3-400f-98a0-6b2f61693955)

## Current Behavior
Now the color starts halfway around, goes to the percentage defined, but then ... inverts so that the only color left showing is the remainder. So if you have something at 100$, it shows nothing. 

![2024-09-26_15-05-58](https://github.com/user-attachments/assets/09fbadeb-53cd-411e-ae85-362dc397dd87)

## Steps to Reproduce

1.
2.
3.
4.

### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [X] Safari 11
- [X] Safari 18
- [ ] Safari 10
- [ ] IE 11

**Comment by hossainemruz** [comment]
Probably some CSS issue. Try updating to latest version.

**Comment by davidgs** [comment]
I'm on the latest version. Still happening.

**Comment by hossainemruz** [comment]
@davidgs Are you still facing the issue? I see the animation is working fine on your portfolio.

**Comment by serverfriendsorg** [comment]
@davidgs Not sure if this still relevant to you but I experienced the same issue and was able to resolve it by updating the about section from:

```
 softSkills:
 - name: Teamwork
   percentage: 90
   color: yellow
 - name: Communication
   percentage: 90
   color: "#e67e22"
```

to

```
badges:
- type: soft-skill-indicator
  name: Teamwork
  percentage: 90
  color: yellow
- type: soft-skill-indicator
  name: Communication
  percentage: 90
  color: "#e67e22"
```

Hope that helps!
